steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - './copy_artifacts.sh'
  
  - name: gcr.io/cloud-builders/docker
    args: ['build', '--build-arg', '_MODEL_NAME=${_MODEL_NAME}', '-t', '${_REGION}-docker.pkg.dev/${_PROJECTID}/${_REPOSITORY}/${_IMAGE}:${COMMIT_SHA}', '.']
    id: Build

  - name: gcr.io/cloud-builders/docker
    args: ['push', '${_REGION}-docker.pkg.dev/${_PROJECTID}/${_REPOSITORY}/${_IMAGE}:${COMMIT_SHA}']
    id: Push

substitutions:
  _MODEL_NAME: 'default-model'
  _REGION: 'europe-west4'
  _PROJECTID: 'default-project-id'
  _REPOSITORY: 'default-repo'
  _IMAGE: 'default-image'
images:
  - '${_REGION}-docker.pkg.dev/${_PROJECTID}/${_REPOSITORY}/${_IMAGE}:${COMMIT_SHA}'