name: Deploy

on:
  push:
    branches:
      - main
    paths:
    - 'predict/**'

env: #change these by your own
  PROJECT_ID: projectid
  REGION: europe-west4
  REPOSITORY: repo
  IMAGE: zephyrgptqpredict
  MODEL_NAME: zephyr-gptq
  MODEL_ID: modelid
  PREDICT_ROUTE: /predict
  HEALTH_ROUTE: /health
  PORTS: 7080

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true


    - name: Trigger Cloud Build
      working-directory: ./predict
      run: |
        gcloud builds submit \
          --config cloudbuild.yaml \
          --substitutions=_MODEL_NAME=${{ env.MODEL_NAME }},_REGION=${{ env.REGION }},_PROJECTID=${{ env.PROJECT_ID }},_REPOSITORY=${{ env.REPOSITORY }},_IMAGE=${{ env.IMAGE }},COMMIT_SHA="${GITHUB_SHA}"


    - name: Register model into Model Registry
      env: 
        VAR_IMG: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE}}:${{ github.sha }}
      run: |
        gcloud ai models upload --container-image-uri="${{ env.VAR_IMG }}" \
        --container-health-route="${{ env.HEALTH_ROUTE }}" \
        --container-predict-route="${{ env.PREDICT_ROUTE }}" \
        --container-ports=${{ env.PORTS }} \
        --display-name=${{ env.MODEL_NAME }} \
        --model-id=${{ env.MODEL_ID }} \
        --region=${{ env.REGION }} \
        --project=${{ env.PROJECT_ID }}
