name: Finetune

on:
  push:
    branches:
      - main
    paths:
    - 'train/**'

env: # change these by your own
  PROJECT_ID: projectid
  REGION: europe-west4
  REPOSITORY: repo
  IMAGE: zephyrgptqtrain
  MODEL_NAME: zephyr-gptq

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true


    - name: Trigger Cloud Build
      working-directory: ./train
      run: |
        gcloud builds submit \
          --config cloudbuild.yaml \
          --substitutions=_MODEL_NAME=${{ env.MODEL_NAME }},_REGION=${{ env.REGION }},_PROJECTID=${{ env.PROJECT_ID }},_REPOSITORY=${{ env.REPOSITORY }},_IMAGE=${{ env.IMAGE }},COMMIT_SHA="${GITHUB_SHA}"